### PR TITLE
Live keynotes changes

### PR DESCRIPTION
**Pull request by santipalenque**
https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=2644530

### CODE REVIEW

**Comment by iamweswilson** [comment]
@santipalenque I replaced the for Red Hat logos with new images in the CMS, but they are not found screenshot


<details><summary>Browser metadata</summary>





```
Path:      /live/keynotes
Browser:   Safari 15.0 on Mac OS 10.15.7
Viewport:  1275 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-102--openinfra-dev.netlify.app%2Flive%2Fkeynotes&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1275x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-102--openinfra-dev.netlify.app/live/keynotes) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6151e0601bcc910007b36089&commentID=6151e2358b8ed48373ae3342&resolution=resolved)

**Comment by iamweswilson** [comment]
Let's remove the requirement for a presentation link, most will not have anything to link to screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/openinfra-live-keynotes-page
Browser:   Safari 15.0 on Mac OS 10.15.7
Viewport:  1275 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-102--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Fopeninfra-live-keynotes-page&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1275x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-102--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/openinfra-live-keynotes-page) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6151e0601bcc910007b36089&commentID=6151e4aaf581d8dd06e68a6c&resolution=resolved)

**Comment by iamweswilson** [comment]
Running into the same issue with Speaker images screenshot

<details><summary>Browser metadata</summary>





```
Path:      /live/keynotes
Browser:   Safari 15.0 on Mac OS 10.15.7
Viewport:  1275 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-102--openinfra-dev.netlify.app%2Flive%2Fkeynotes&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1275x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-102--openinfra-dev.netlify.app/live/keynotes) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6151e4ba77ca3c0008749260&commentID=6151e68009f04792c27ab3ff&resolution=resolved)

**Comment by iamweswilson** [comment]
It's hard to see how these will look when the images are showing, but it looks like we will need a margin in between rows  screenshot


<details><summary>Browser metadata</summary>





```
Path:      /live/keynotes
Browser:   Safari 15.0 on Mac OS 10.15.7
Viewport:  1275 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-102--openinfra-dev.netlify.app%2Flive%2Fkeynotes&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1275x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-102--openinfra-dev.netlify.app/live/keynotes) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6151e4ba77ca3c0008749260&commentID=6151e6c18b8ed48872ae30ba&resolution=resolved)

**Comment by iamweswilson** [comment]
@santipalenque I'm still getting the error that a presentation link is required, but everything else looks good

**Comment by santipalenque** [comment]
hey @iamweswilson  that should be fixed with my last commit

**Comment by iamweswilson** [comment]
@santipalenque Can we hide the "Featured Speakers" section when there are no speakers in the list? screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/openinfra-live-keynotes-page
Browser:   Safari 15.0 on Mac OS 10.15.7
Viewport:  1272 x 1264 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-102--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Fopeninfra-live-keynotes-page&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1272x1264&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-102--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/openinfra-live-keynotes-page) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61521f71b87535000888189a&commentID=615344d60cf5a600f0ab4dc5&resolution=resolved)

**Comment by santipalenque** [comment]
done @iamweswilson

**Comment by iamweswilson** [comment]
thanks @santipalenque, I tried to remove all speakers in the CMS and still saw the speakers section in place, so published those changes to see if it would work as expected when deployed. Now seeing all checks have failed. https://github.com/OpenStackweb/osf-website/pull/102/commits/45ea8dc6d067abeb0bf116195109453d6bfd2cdb

**Comment by smarcet** [comment]
@iamweswilson @santipalenque issue should be solved
regards

**Comment by iamweswilson** [comment]
@santipalenque @smarcet I'm still seeing the speakers section in the preview when there are no speakers. screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/openinfra-live-keynotes-page
Browser:   Safari 15.0 on Mac OS 10.15.7
Viewport:  1275 x 1264 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-102--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Fopeninfra-live-keynotes-page&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1275x1264&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-102--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/openinfra-live-keynotes-page) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6154402e842bc20007475a5c&commentID=6154d801fd201d1e5c7361ed&resolution=resolved)

**Comment by iamweswilson** [comment]
Merging this PR now since the speaker section is removed when deployed. Thanks!

**Pull request merged**
