### PR TITLE
New project hosting page

### PR DESCRIPTION
**Pull request by santipalenque**
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2927762&fileview=grid

### CODE REVIEW

**Comment by iamweswilson** [comment]
Add links to drop users to relevant sections below:
"sustainability model (3 Forces)" -> 3 forces section
" collaboration principles (4 Opens)" -> 4 Opens section
"our network" -> Worldwide OpenInfra Community section

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/hosting/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1280 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-266--openinfra-dev.netlify.app%2Fprojects%2Fhosting%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1280x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-266--openinfra-dev.netlify.app/projects/hosting/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=628585026c796a0008027f14&commentID=628674a0334bfc005f0a3bcb&resolution=resolved)

**Comment by iamweswilson** [comment]
- center icons with text
- add margin between icons and text
- text should be all caps
- center icons and text within the flex container

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/hosting/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1280 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-266--openinfra-dev.netlify.app%2Fprojects%2Fhosting%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1280x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-266--openinfra-dev.netlify.app/projects/hosting/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=628585026c796a0008027f14&commentID=6286753d8b0c470059572c67&resolution=resolved)

**Comment by iamweswilson** [comment]
Reduce space between "Our network" and "Worldwide openinfra community" to match other sections

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/hosting/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1282 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-266--openinfra-dev.netlify.app%2Fprojects%2Fhosting%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1282x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-266--openinfra-dev.netlify.app/projects/hosting/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=628585026c796a0008027f14&commentID=628675c8fa1410006455e860&resolution=resolved)

**Comment by iamweswilson** [comment]
- set max-width to 115px for logos, they're too large now
- missing some logos (guessing because we're in dev)
- add fixed gradient at left and right of container, as shown in design

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/hosting/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1282 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-266--openinfra-dev.netlify.app%2Fprojects%2Fhosting%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1282x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-266--openinfra-dev.netlify.app/projects/hosting/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=628585026c796a0008027f14&commentID=62867656d7193f00a7294878&resolution=resolved)

**Comment by iamweswilson** [comment]
remove left padding on these labels (not globally) so that icons and text are left aligned

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/hosting/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1282 x 997 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-266--openinfra-dev.netlify.app%2Fprojects%2Fhosting%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1282x997&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-266--openinfra-dev.netlify.app/projects/hosting/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=628585026c796a0008027f14&commentID=628676c3dc82b70bbe0ff568&resolution=resolved)

**Comment by iamweswilson** [comment]
Green section is missing top-left, top-right border radius

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/hosting/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1282 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-266--openinfra-dev.netlify.app%2Fprojects%2Fhosting%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1282x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-266--openinfra-dev.netlify.app/projects/hosting/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=628585026c796a0008027f14&commentID=628676f2f1c2e20b1beb8ee2&resolution=resolved)

**Comment by iamweswilson** [comment]
- remove horizontal line between middle rows
- vertically center all items

screenshot is showing design on the right, fyi
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/hosting/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1282 x 1261 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-266--openinfra-dev.netlify.app%2Fprojects%2Fhosting%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1282x1261&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-266--openinfra-dev.netlify.app/projects/hosting/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=628585026c796a0008027f14&commentID=628677aaa0e4bc0095ada484&resolution=resolved)

**Comment by santipalenque** [comment]
@iamweswilson @smarcet  please check again, thanks!

**Pull request closed without merging**
