### PR TITLE
Openinfrra Live - CMS integration

### PR DESCRIPTION
**Pull request by tomrndom**
* Refactoring openinfra-live template to work with data on markdown file
* Integration with the CMS

Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>

### CODE REVIEW

**Comment by iamweswilson** [comment]
All of these fields are required for the page before publishing, but it doesn't look like they are populating the page. I haven't checked if that's true for the SEO fields, but the "Hero" fields don't seem to affect the page. Should they be optional?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60c8e07442708500075fd66f&commentID=60c8ee06035b1600c3659db9&resolution=resolved)

**Comment by iamweswilson** [comment]
When an episode is collapsed as shown, this arrow isn't opening the episode details. Should it? 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60c8e07442708500075fd66f&commentID=60c8ee4245de3e00b2b89ef9&resolution=resolved)

**Comment by iamweswilson** [comment]
Is it possible to change this to 24-hour clock so that the person adding the episode can select "1400 UTC" in the dropdown, rather than having to convert it to 12-hours?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60c8e07442708500075fd66f&commentID=60c8eea65e513b009c8dfd55&resolution=resolved)

**Comment by iamweswilson** [comment]
Is it possible to open the new episode UI at the top of the list? And sort the episodes desc from most recent (top) to earliest (bottom) by default?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60c8f942a9124f00074da889&commentID=60c915f5a47d1e28f46f4fed&resolution=resolved)

**Comment by iamweswilson** [comment]
Should this hero section control the page hero? Looks like they're different text now. 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60c8f942a9124f00074da889&commentID=60c91632aa7bae2f427e0df5&resolution=resolved)

**Comment by iamweswilson** [comment]
What's the best way to handle this scenario, when there is not a future episode in the system (or the episode is hidden)? Can we remove "The Next Episode..." and "While you're waiting..." text and replace it with an `h2` that reads "Check out the most recent episodes"?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60c8f942a9124f00074da889&commentID=60c917590b7a0e293e889c16&resolution=resolved)

**Comment by iamweswilson** [comment]
Hide "Add to Calendar" UI when a file has not been added to the episode

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60c8f942a9124f00074da889&commentID=60c917e38880532b4a2f3388&resolution=resolved)

**Comment by iamweswilson** [comment]
Hide "Featuring" when speakers input is blank

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60c8f942a9124f00074da889&commentID=60c9181a37e04b2c323283ab&resolution=resolved)

**Comment by iamweswilson** [comment]
Can we add a clickable label or similar in/around this field to say "Create a calendar invite at https://ical.marudot.com"

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60c8f942a9124f00074da889&commentID=60c9196e5af1882d832081a7&resolution=resolved)

**Comment by iamweswilson** [comment]
Can we change when the featured/next episode switches, so it changes after the current episode has aired? For example, we're showing the June 24th episode at the top, but there is an episode currently streaming. Let's change it to switch at 16:00 UTC (one hour after the current episode ends).

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/index
Browser:   Safari 14.1 on Mac OS 10.15.7
Viewport:  1440 x 735 @2x
Language:  en-us
Cookies:   Disabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-69--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Findex&os=OS+X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1440x735&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-69--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/index) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60cb5c2f82e81e0007b6370c&commentID=60cb5fae8233fa18596639d2&resolution=resolved)

**Review by smarcet — APPROVED** [review]
Looks good to me

**Pull request merged**
