### PR TITLE
Adjusted styles for projects page to add whitespace and color

### PR DESCRIPTION
**Pull request by yoshwaaa**

### CODE REVIEW

**Comment by iamweswilson** [comment]
Let's use the icon-only instead of the full mark. This logo (and all project logos) can be found in Dropbox: Foundation > Design > [project] > logos. Here's a direct link: https://www.dropbox.com/s/6oswrzqnmvekjrf/OpenInfraLabs-Icon-RGB-Color.svg?dl=0

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/
Browser:   Safari 15.5 on Mac OS 10.15.7
Viewport:  1439 x 723 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-302--openinfra-dev.netlify.app%2Fprojects%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1439x723&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-302--openinfra-dev.netlify.app/projects/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62d18588387139000984b7ab&commentID=62d190e47de22d3ed984d864&resolution=resolved)

**Comment by iamweswilson** [comment]
Now that we're adding color to the links, it's more apparent the lighter links are tougher to view. Let's use the blue from the logo instead. 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/
Browser:   Safari 15.5 on Mac OS 10.15.7
Viewport:  1439 x 723 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-302--openinfra-dev.netlify.app%2Fprojects%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1439x723&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-302--openinfra-dev.netlify.app/projects/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62d18588387139000984b7ab&commentID=62d1913a0422273cbbaa892e&resolution=resolved)

**Comment by iamweswilson** [comment]
The set width % is creating some misalignment in these buttons. 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/
Browser:   Safari 15.5 on Mac OS 10.15.7
Viewport:  1439 x 723 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-302--openinfra-dev.netlify.app%2Fprojects%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1439x723&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-302--openinfra-dev.netlify.app/projects/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62d18588387139000984b7ab&commentID=62d19182e5d6e43e1764d15a&resolution=resolved)

**Comment by iamweswilson** [comment]
Should this text be openifralabs.org to match the other buttons?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/
Browser:   Safari 15.5 on Mac OS 10.15.7
Viewport:  1439 x 723 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-302--openinfra-dev.netlify.app%2Fprojects%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1439x723&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-302--openinfra-dev.netlify.app/projects/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62d18588387139000984b7ab&commentID=62d191d64624d444b915412c&resolution=resolved)

**Comment by yoshwaaa** [comment]
Hey Wes! Great feedback - all of these updates should be added in now - button centering is fixed, OpenInfra Labs logo is swapped, and colors/button text has been adjusted as well. Let me know if you see anything else at all. Thank you!

**Comment by iamweswilson** [comment]
Let's left align logos on smaller screens
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/
Browser:   Safari 15.5 on Mac OS 10.15.7
Viewport:  574 x 723 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-302--openinfra-dev.netlify.app%2Fprojects%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=574x723&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-302--openinfra-dev.netlify.app/projects/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62d1a131ea65db0008779314&commentID=62d1b0f84624d4614b15409c&resolution=resolved)

**Comment by iamweswilson** [comment]
Looks like we need to adjust the svg to remove the whitespace. As it is now, the logo looks much smaller because of that. Removing it will match the size of the other logos on the page. Let me know if I can help with this. 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /projects/
Browser:   Safari 15.5 on Mac OS 10.15.7
Viewport:  574 x 723 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-302--openinfra-dev.netlify.app%2Fprojects%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=574x723&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-302--openinfra-dev.netlify.app/projects/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62d1a131ea65db0008779314&commentID=62d1b150f047fa5c9f581919&resolution=resolved)

**Pull request merged**
