### PR TITLE
Homepage revamp 2022

### PR DESCRIPTION
**Pull request by yoshwaaa**

### CODE REVIEW

**Comment by iamweswilson** [comment]
Let's remove the top margin in `.home-v2-hero-wrapper .hero-content`

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=63581e907b36790c6c534ce7&resolution=resolved)

**Comment by iamweswilson** [comment]
White border appears in this section 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=63581ef02cd5c000b84f7a4c&resolution=resolved)

**Comment by iamweswilson** [comment]
This paragraph is actually not intended to change as the icons switch, so the words in the design are correct

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=63581f964336df0c9030a55b&resolution=resolved)

**Comment by iamweswilson** [comment]
These icons are intended to match the icons in the "Why Expand Beyond OpenStack" section of https://openinfra.dev/. So the active icon you're using, should be the first icon in its active state. The same should happen to all of the other icons (use the current icon, inverted). Hover titles will also match the current home page:

- Edge Computing
- Container Infrastructure
- Public/Private Hybrid Cloud
- AI & Machine Learning
- CI/CD

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=63582063d28a8e068650f611&resolution=resolved)

**Comment by iamweswilson** [comment]
Match the hover states provided in the design system file: https://www.figma.com/file/TaVA23ukHX7zh155i9XMqq/OpenInfra-Design-System?node-id=19%3A1187

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=635820bc5b61440c94a48f5b&resolution=resolved)

**Comment by iamweswilson** [comment]
I would have these move to the next project quicker. Also, each project section should link to /projects/ 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=6358210b6813540b26818960&resolution=resolved)

**Comment by iamweswilson** [comment]
These should autoscroll as well, at a pace similar to the member logos

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=6358218d6813540b26818b3c&resolution=resolved)

**Comment by iamweswilson** [comment]
Noticed this one logo misaligned, but this section looks really good! When you're ready, we can have Tipit work on integrating the logo management tool here as well

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=635821d22cd5c004f64f798a&resolution=resolved)

**Comment by iamweswilson** [comment]
Can we also link the preview image and article title to the same destination as "Read More"?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=63582214f451d405bdfcc21f&resolution=resolved)

**Comment by iamweswilson** [comment]
Leaving this comment so we remember to update the rest of the site to use the new top nav and footer

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /members/
Browser:   Chrome 106.0.0.0 on Mac OS 10.15.7
Viewport:  1324 x 739 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2Fmembers%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=106.0&resolution=1324x739&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/members/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=635822bb5b61440cf6a49126&resolution=resolved)

**Comment by iamweswilson** [comment]
Noticed an interesting activity on the page... When you only slightly scroll up or down (not fully in a section), the page will push you to the top of that section automatically. Not sure if it's intended, but feels confusing and overly controlling. Can we remove that action? recording


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 107.0.0.0 on Mac OS 10.15.7
Viewport:  1321 x 793 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-355--openinfra-dev.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=107.0&resolution=1321x793&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=636000d163596c000968d093&commentID=6362bf65ccd5634f8203965a&resolution=resolved)

**Comment by yoshwaaa** [comment]
> Noticed this one logo misaligned, but this section looks really good! When you're ready, we can have Tipit work on integrating the logo management tool here as well
> 
> screenshot
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=635821d22cd5c004f64f798a&resolution=resolved)

The member logos are a little wonky right now and some aren't showing up, but that's because we're getting ready to add in logos using the management tool in Show Admin! This will be resolved soon!

**Comment by yoshwaaa** [comment]
> > Noticed this one logo misaligned, but this section looks really good! When you're ready, we can have Tipit work on integrating the logo management tool here as well
> > screenshot
> > Browser metadata
> > [Open Deploy Preview](https://deploy-preview-355--openinfra-dev.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6356f543e7f3bb0008b71c6b&commentID=635821d22cd5c004f64f798a&resolution=resolved)
> 
> The member logos are a little wonky right now and some aren't showing up, but that's because we're getting ready to add in logos using the management tool in Show Admin! This will be resolved soon!

Logos are now loading into the new homepage straight from Show Admin :)

**Pull request merged**
