### PR TITLE
Small adjustment to secondary button spacing on bottom of join page

### PR DESCRIPTION
**Pull request by yoshwaaa**

### CODE REVIEW

**Comment by yoshwaaa** [comment]
@iamweswilson small width adjustment to the secondary button on the join page, in the "Get Involved" section

**Comment by iamweswilson** [comment]
Looks good @yoshwaaa ! The only discrepancy I found in the subnav spacing was with https://deploy-preview-290--openinfra-dev.netlify.app/summit/vancouver-2023 (another page I threw together, so the difference is likely my fault). 
<details><summary>Browser metadata</summary>





```
Path:      /summit/vancouver-2023
Browser:   Safari 15.5 on Mac OS 10.15.7
Viewport:  1287 x 1260 @2x
Language:  en-US
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-290--openinfra-dev.netlify.app%2Fsummit%2Fvancouver-2023&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1287x1260&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-290--openinfra-dev.netlify.app/summit/vancouver-2023) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=62b613fce601f100087011a7&commentID=62b6248696ff0d1364e2e046&resolution=resolved)

**Comment by yoshwaaa** [comment]
Great catch, @iamweswilson! Making that adjustment now

**Comment by iamweswilson** [comment]
Update looks great, thanks @yoshwaaa !

**Review by iamweswilson — APPROVED** [review]

**Comment by yoshwaaa** [comment]
You betcha, @iamweswilson! Thank you for the great catch on the Vancouver Summit page

**Pull request merged**
