### PR TITLE
Move keynotes page to CMS

### PR DESCRIPTION
**Pull request by santipalenque**

### CODE REVIEW

**Comment by iamweswilson** [comment]
Should the url shown the CMS preview? It's not showing for me screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-keynotes-page/entries/asdf
Browser:   Safari 14.1.2 on Mac OS 10.15.7
Viewport:  1280 x 1272 @2x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-95--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-keynotes-page%2Fentries%2Fasdf&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1280x1272&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-95--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-keynotes-page/entries/asdf) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6140b5123180d200084b47bb&commentID=6140c798f5ffea00ca2a8640&resolution=resolved)

**Comment by iamweswilson** [comment]
Can we allow html in this section? screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-keynotes-page/entries/asdf
Browser:   Safari 14.1.2 on Mac OS 10.15.7
Viewport:  1280 x 1272 @2x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-95--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-keynotes-page%2Fentries%2Fasdf&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1280x1272&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-95--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-keynotes-page/entries/asdf) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6140b5123180d200084b47bb&commentID=6140c7d0f5ffea00a32a85d1&resolution=resolved)

**Comment by iamweswilson** [comment]
Can we make sure this is not the image used when this is moved to production? 🤣 screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-keynotes-page/entries/asdf
Browser:   Safari 14.1.2 on Mac OS 10.15.7
Viewport:  1280 x 1272 @2x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-95--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-keynotes-page%2Fentries%2Fasdf&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1280x1272&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-95--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-keynotes-page/entries/asdf) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6140b5123180d200084b47bb&commentID=6140c890679b110095265dd7&resolution=resolved)

**Comment by santipalenque** [comment]
hey @iamweswilson the link in preview is only for links (<a> tags) not for buttons like this one. The rest was taken care of
<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-keynotes-page/entries/asdf
Browser:   Chrome 92.0.4515.131 on Linux x86_64
Viewport:  1848 x 949 @1x
Language:  es-AR
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-95--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-keynotes-page%2Fentries%2Fasdf&os=OS%20X&os_version=Big%20Sur&browser=Chrome&browser_version=92.0&resolution=1848x949&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-95--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-keynotes-page/entries/asdf) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6140d3687284c30008083a1a&commentID=6140f81196486129c33d0685&resolution=resolved)

**Comment by iamweswilson** [comment]
Looks like adding a link is displaying as markdown on in the preview. Is this intended? screenshot


<details><summary>Browser metadata</summary>





```
Path:      /admin/#/collections/openinfra-live-page/entries/openinfra-live-keynotes-page
Browser:   Safari 14.1.2 on Mac OS 10.15.7
Viewport:  1280 x 1272 @2x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-95--openinfra-dev.netlify.app%2Fadmin%2F%23%2Fcollections%2Fopeninfra-live-page%2Fentries%2Fopeninfra-live-keynotes-page&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=14.0&resolution=1280x1272&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-95--openinfra-dev.netlify.app/admin/#/collections/openinfra-live-page/entries/openinfra-live-keynotes-page) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6140f96fbfc35e00085c04e3&commentID=61411c2d0487a90e87b309aa&resolution=resolved)

**Review by smarcet — APPROVED** [review]
looks good to me

**Review by smarcet — APPROVED** [review]

**Pull request merged**
